; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp12e

[env:esp01_1m]
platform = espressif8266
framework = arduino
board = esp01_1m
lib_deps = 
	Wire
	SPI
	ESPAsyncUDP
	AsyncMqttClient
	ArduinoJson
	ShiftRegister74HC595
	ESP Async WebServer
	WebSockets
	FauxmoESP
	DHT=https://github.com/bertmelis/DHT/archive/master.zip

[env:esp12e]
platform = espressif8266
framework = arduino
board = esp12e
lib_deps = 
	Wire
	SPI
	ESPAsyncUDP
	AsyncMqttClient
	ArduinoJson
	ShiftRegister74HC595
	ESP Async WebServer
	WebSockets
	FauxmoESP
	DHT=https://github.com/bertmelis/DHT/archive/master.zip

[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
lib_deps = 
	Wire
	SPI
	ESPAsyncUDP
	AsyncMqttClient
	ArduinoJson
	ShiftRegister74HC595
	ESP Async WebServer
	WebSockets
	FauxmoESP
	DHT=https://github.com/bertmelis/DHT/archive/master.zip

[env:huzzah]
platform = espressif8266
framework = arduino
board = huzzah
lib_deps = 
	Wire
	SPI
	ESPAsyncUDP
	AsyncMqttClient
	ArduinoJson
	ShiftRegister74HC595
	ESP Async WebServer
	WebSockets
	FauxmoESP
	DHT=https://github.com/bertmelis/DHT/archive/master.zip

[env:thing]
platform = espressif8266
framework = arduino
board = thing
lib_deps = 
	Wire
	SPI
	ESPAsyncUDP
	AsyncMqttClient
	ArduinoJson
	ShiftRegister74HC595
	ESP Async WebServer
	WebSockets
	FauxmoESP
	DHT=https://github.com/bertmelis/DHT/archive/master.zip
