;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nodemcuv2

[env:esp01]
platform = espressif8266
framework = arduino
board = esp01
board_build.filesystem = SPIFFS
lib_deps = 
	Wire
	SPI
	ESPAsyncUDP
	AsyncMqttClient
	ESP_EEPROM
	id=64
	Adafruit Unified Sensor
	DHT sensor library
	ShiftRegister74HC595
	id=1438
	id=567
	id=305
	id=306

[env:esp12e]
platform = espressif8266
framework = arduino
board = esp12e
board_build.filesystem = SPIFFS
lib_deps = 
	Wire
	SPI
	ESPAsyncUDP
	AsyncMqttClient
	ESP_EEPROM
	id=64
	Adafruit Unified Sensor
	DHT sensor library
	ShiftRegister74HC595
	id=1438
	id=567
	id=305
	id=306

[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
board_build.filesystem = SPIFFS
lib_deps = 
	Wire
	SPI
	ESPAsyncUDP
	AsyncMqttClient
	ESP_EEPROM
	id=64
	Adafruit Unified Sensor
	DHT sensor library
	ShiftRegister74HC595
	id=1438
	id=567
	id=305
	id=306

[env:huzzah]
platform = espressif8266
framework = arduino
board = huzzah
board_build.filesystem = SPIFFS
lib_deps = 
	ESPAsyncUDP
	AsyncMqttClient
	ESP_EEPROM
	id=64
	Adafruit Unified Sensor
	DHT sensor library
	ShiftRegister74HC595
	Wire
	id=1438
	id=567
	id=305
	id=306

[env:thing]
platform = espressif8266
framework = arduino
board = thing
board_build.filesystem = SPIFFS
lib_deps = 
	ESPAsyncUDP
	AsyncMqttClient
	ESP_EEPROM
	id=64
	Adafruit Unified Sensor
	DHT sensor library
	ShiftRegister74HC595
	id=1438
	id=567
	id=305
	id=306

