; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
env_default = ssl

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino

[env:ssl]
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
framework = arduino
board = esp01_1m
build_flags = -DASYNC_TCP_SSL_ENABLED=1
lib_deps = AsyncMqttClient

[env:nossl]
platform = espressif8266
framework = arduino
board = esp01_1m
lib_deps = AsyncMqttClient